server:
  port: 8082

spring:
  application:
    name: orders-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000